version: '3'

services:
  jenkins:
    build:
      context: ./jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket
    ports:
      - "8080:8080"
    networks:
      - jenkins
    depends_on:
      - dind

  dind:
    image: docker:20.10-dind
    networks:
      - jenkins
    privileged: true

networks:
  jenkins:

volumes:
  jenkins_home:
